"""initial schema

Revision ID: 0f0f82cb326c
Revises: 
Create Date: 2026-08-09 00:34:01.870053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0f82cb326c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPERATIONAL_MANAGER', 'STAFF', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', name='userstatus'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('last_ip_address', sa.String(length=50), nullable=True),
    sa.Column('last_device', sa.String(length=150), nullable=True),
    sa.Column('last_browser', sa.String(length=150), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_number'), ['employee_number'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('TASK', 'WEEKLY_PLAN', 'REPORT', name='commenttargettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comment_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_target_id'), ['target_id'], unique=False)

    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=120), nullable=True),
    sa.Column('operating_system', sa.String(length=120), nullable=True),
    sa.Column('device', sa.String(length=120), nullable=True),
    sa.Column('login_successful', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_history_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('SYSTEM', 'ASSIGNED_TASK', 'WEEKLY_PLAN', 'PLAN_REVIEW', 'PERFORMANCE', 'REMINDER', 'SECURITY', 'ANNOUNCEMENT', 'COMMENT', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='notificationdeliverystatus'), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_delivery_attempt', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_created', ['created_at'], unique=False)
        batch_op.create_index('idx_notification_delivery', ['delivery_status'], unique=False)
        batch_op.create_index('idx_notification_read', ['read'], unique=False)
        batch_op.create_index('idx_notification_recipient', ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('total_plans', sa.Integer(), nullable=False),
    sa.Column('completed_plans', sa.Integer(), nullable=False),
    sa.Column('total_activities', sa.Integer(), nullable=False),
    sa.Column('completed_activities', sa.Integer(), nullable=False),
    sa.Column('weekly_average', sa.Float(), nullable=True),
    sa.Column('monthly_average', sa.Float(), nullable=True),
    sa.Column('yearly_average', sa.Float(), nullable=True),
    sa.Column('overall_average', sa.Float(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_employee_id'), ['employee_id'], unique=True)

    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ACTIVE', 'APPROVED', 'REJECTED', 'COMPLETED', 'ARCHIVED', name='planstatus'), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'week_number', 'year', name='unique_employee_week')
    )
    with op.batch_alter_table('weekly_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_plans_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_plans_week_number'), ['week_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_plans_year'), ['year'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('employee_status', sa.Enum('PENDING', 'DONE', 'NOT_DONE', name='activitystatus'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'OVERRIDDEN', name='verificationstatus'), nullable=False),
    sa.Column('final_status', sa.Enum('PENDING', 'SUCCESSFUL', 'UNSUCCESSFUL', 'MANAGER_OVERRIDE', name='finalstatus'), nullable=False),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('manager_override', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('evidence_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('idx_activity_date', ['activity_date'], unique=False)
        batch_op.create_index('idx_activity_verification', ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_plan_id'), ['plan_id'], unique=False)

    op.create_table('assigned_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('related_activity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('assigned_time', sa.Time(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'REJECTED', 'CANCELLED', 'OVERDUE', name='taskstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assigned_tasks_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assigned_tasks_manager_id'), ['manager_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assigned_tasks_manager_id'))
        batch_op.drop_index(batch_op.f('ix_assigned_tasks_employee_id'))

    op.drop_table('assigned_tasks')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_plan_id'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_date'))
        batch_op.drop_index('idx_activity_verification')
        batch_op.drop_index('idx_activity_date')

    op.drop_table('activities')
    with op.batch_alter_table('weekly_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_plans_year'))
        batch_op.drop_index(batch_op.f('ix_weekly_plans_week_number'))
        batch_op.drop_index(batch_op.f('ix_weekly_plans_employee_id'))

    op.drop_table('weekly_plans')
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_employee_id'))

    op.drop_table('performance')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index('idx_notification_recipient')
        batch_op.drop_index('idx_notification_read')
        batch_op.drop_index('idx_notification_delivery')
        batch_op.drop_index('idx_notification_created')

    op.drop_table('notifications')
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_history_user_id'))

    op.drop_table('login_history')
    op.drop_table('generated_reports')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_target_id'))
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))
        batch_op.drop_index('idx_comment_target')

    op.drop_table('comments')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_employee_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
