"""add due_time and expected_outcome to activities

Revision ID: 169fa362c6a9
Revises: 4546a1b8067f
Create Date: 2026-08-10 00:05:06.451455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169fa362c6a9'
down_revision = '4546a1b8067f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('expected_outcome', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('expected_outcome')
        batch_op.drop_column('due_time')

    # ### end Alembic commands ###
