"""add expected_outcome to assigned_tasks

Revision ID: 4546a1b8067f
Revises: 79a9ee736a9a
Create Date: 2026-08-09 22:36:14.543283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4546a1b8067f'
down_revision = '79a9ee736a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_outcome', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('expected_outcome')

    # ### end Alembic commands ###
