"""add department scoping to generated_reports

Revision ID: 79a9ee736a9a
Revises: e346bbcf8595
Create Date: 2026-08-09 21:00:00.482290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a9ee736a9a'
down_revision = 'e346bbcf8595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('period_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('period_end', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_generated_reports_department_id'), ['department_id'], unique=False)
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_generated_reports_department_id'))
        batch_op.drop_column('period_end')
        batch_op.drop_column('period_start')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
