"""task submission/approval lifecycle, progress history, audit targets

Revision ID: 817084b1d72b
Revises: be584f9c7e11
Create Date: 2026-08-09 02:42:08.143040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817084b1d72b'
down_revision = 'be584f9c7e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_progress_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('previous_progress', sa.Integer(), nullable=False),
    sa.Column('new_progress', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['assigned_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_progress_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_progress_updates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_progress_updates_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('overdue_notified', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.Enum('TASK', 'WEEKLY_PLAN', 'REPORT', name='commenttargettype'), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_audit_log_target', ['target_type', 'target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_log_target')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')

    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('overdue_notified')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('submitted_at')

    with op.batch_alter_table('task_progress_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_progress_updates_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_progress_updates_created_at'))

    op.drop_table('task_progress_updates')
    # ### end Alembic commands ###
