"""add budget, review_notes, activity weight/task_count, generated_reports

Revision ID: be584f9c7e11
Revises: 0f0f82cb326c
Create Date: 2026-08-09 01:14:58.235501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be584f9c7e11'
down_revision = '0f0f82cb326c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
