"""add task_exceptions table

Revision ID: e346bbcf8595
Revises: ebb08379d5de
Create Date: 2026-08-09 20:42:49.465185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e346bbcf8595'
down_revision = 'ebb08379d5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.Enum('CUSTOMER_DELAY', 'SYSTEM_DOWNTIME', 'AWAITING_APPROVAL', 'INSUFFICIENT_RESOURCES', 'STAFF_UNAVAILABLE', 'EXTERNAL_DEPENDENCY', 'EMERGENCY', 'OTHER', name='noncompletionreasoncategory'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Enum('RESCHEDULED', 'PENDING_DEPENDENCY', 'ESCALATED', 'WAIVED', 'CONTINUE_MONITORING', name='taskresolution'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['assigned_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_exceptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_exceptions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_exceptions_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_exceptions_created_at'))

    op.drop_table('task_exceptions')
    # ### end Alembic commands ###
