"""add plan_id to assigned_tasks

Revision ID: ebb08379d5de
Revises: e83b60dc37e5
Create Date: 2026-08-09 19:38:37.886749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb08379d5de'
down_revision = 'e83b60dc37e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assigned_tasks_plan_id'), ['plan_id'], unique=False)
        batch_op.create_foreign_key(None, 'weekly_plans', ['plan_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assigned_tasks_plan_id'))
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
